services:
  postgres:
    networks:
      - yggdrasil

  app:
    image: ghcr.io/valdi-at/kewirausahaan-berbasis-teknologi-28-ritsu:master
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ritsu-app.rule=Host(`ritsu.shinyshoe.net`)"
      - "traefik.http.routers.ritsu-app.entrypoints=websecure"
      - "traefik.http.routers.ritsu-app.service=ritsu-app"
      - "traefik.http.routers.ritsu-app.tls=true"
      - "traefik.http.services.ritsu-app.loadbalancer.server.port=3000"
    networks:
      - yggdrasil

  pgadmin:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ritsu-pgadmin.rule=Host(`ritsu-pgadmin.shinyshoe.net`)"
      - "traefik.http.routers.ritsu-pgadmin.entrypoints=websecure"
      - "traefik.http.routers.ritsu-pgadmin.service=ritsu-pgadmin"
      - "traefik.http.routers.ritsu-pgadmin.tls=true"
      - "traefik.http.services.ritsu-pgadmin.loadbalancer.server.port=80"
    networks:
      - yggdrasil

networks:
  yggdrasil:
    name: yggdrasil-heimdall
    external: true